### ISSUE TITLE
OverlapComponent Backprop Implementation

### ISSUE THREAD

**Issue by apoorv2904** [LdyXOR/adversarialattacks#5]
Hi,

I was going through the backward pass in the OverlapComponent class defined in nnet2-component.cc and was a bit confused with the implementation.  I had a few questions with the following code.

  CuSubMatrix<BaseFloat>  in_part2(*in_deriv, 0, in_deriv->NumRows()-1,
                                 0, in_deriv->NumCols()),
                         out_part1(out_deriv, 0, out_deriv.NumRows()-1,
                                  0, in_deriv->NumCols());

  in_part2.CopyFromMat(out_part1);

-- Is the in_derivative matrix filled with first N-1 rows of the out_derivative ?
-- If the answer to first question is yes, then shouldn't it be affected by the overlapping part in out_deriv i.e. columns  in_deriv->NumCols() to  out_deriv->NumCols() 

Thanks,
Apoorv

**Comment by lealeasch** [comment]
Hi,

I am not sure if I understand your question correctly. But if you are asking what is happening to the overlapping part of the derivation, this part is simply discarded. You can also combine the two overlapping derivations and use e.g. the mean of both values. However, we havn't tested this case.

I hope this answered your question.

Best regards,
Lea

**Comment by apoorv2904** [comment]
Hi,

First of all thank you for the quick reply. Yes, that was indeed my question. I asked this because, following chain rule the derivative at the overlapping points should have been summed up. Currently, the last row of the out derivate seems to be not copied as well.

Also, do you have any plans to extend this to nnet3 setup as well ?

Best Regards,
Apoorv

**Comment by lealeasch** [comment]
Hi,

yes, you are right from a mathematical point of view. However, for the implementation, I did not want the neighboured frames to influence the current frame, also due to the hearing thresholds. About the last frame: nnet2 adds context at the beginning and the and. Therefore, the last frame will be discarded anyway.

For nnet3, the algorithm can be used similarly as for nnet2. The update of the audio will be a little bit different, but  I know that you can use the new components for nnet3-component.cc, too, if you copy the code.

Unfortunately, I can not tell you, if we will add the code for nnet3 soon.

Best regards,
Lea

**Comment by apoorv2904** [comment]
Thank you for the details. I think I will be able to extend the code to nnet3. I will close the issue. Once again, thank you for the clarifications.

Best regards,
Apoorv
